d_model: 1152 # Input dimension to DiT
l_max: 1000000 # Maximum input sequence length. 
order: 2 # Depth of the Hyena recurrence.
inner_factor:  1 # Width multiplier. Defaults to 1
num_heads: 1
num_blocks: 1
inner_filter_len:  4 # Length of the inner convolutional filter. Defaults to 4