operator:
  type: 'mlp'
  name: "mlp_hyena_x"
  config_filepath: configs/channel_mixers/mlp_hyena_x.yaml


sample_config:
  init_type: graft
  global_seed: 100
  dit_model_name: DiT-XL/2
  grafted_dit_ckpt_path: gits/dit-xl2-mlp-hyena_x-50p-fid2.64/model.pt
  samples_save_dir: results/dit-xl2-mlp-hyena_x-50p-fid2.64
  image_size: 256
  graft_indexes:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 17
    - 19
    - 21
    - 23
    - 25
    - 27
  graft_weights:


